### ISSUE TITLE
No PASS reports since Browsermob-Proxy-0.13

### ISSUE THREAD

**Issue by eserte** [gempesaw/Browsermob-Proxy#2]
Version 0.12 was the last one which was mostly green on the cpantesters matrix: http://matrix.cpantesters.org/?dist=Browsermob-Proxy%200.12
Since version 0.13 this changed: http://matrix.cpantesters.org/?dist=Browsermob-Proxy%200.13

**Comment by gempesaw** [comment]
ah, thanks for the heads up. 

I had opened a PR to Net::HTTP::Spore to add a new middleware format, but it hasn't been merged or released to CPAN, seems like the Spore maintainers are busy, so the tests are justifiably sad about missing that module. I guess I'll just release it to CPAN as a standalone module.

**Comment by gempesaw** [comment]
humm, just uploaded this to cpan: https://metacpan.org/pod/Net::HTTP::Spore::Middleware::Format::Text

will push a new release of this module with explicit dependency shortly. thanks!
